# 1.2 Neuron Network
In Neuron Network consist of input layer, hidden layer and output layer.

In [29]:
import numpy as np
import matplotlib.pyplot as plt

## 1.2.1 Hidden Layer

$ h = xW + b$   
Input: $x$   
Weight: $W$   
Bias : $b$  
Neurons in hidden layers : $h$

In [25]:
#build a hidden layer 
N_1 = 10
N_2 = 5
N_3 = 5

# Understand the matrix's dimensional
W1 = np.random.randn(N_2, N_3) 
b1 = np.random.randn(N_3)
x = np.random.randn(N_1, N_2)

h = np.dot(x, W1) + b1
h

array([[ 3.11682349,  0.92188361, -1.25635871,  0.38099956,  0.78909449],
       [ 3.51927995, -1.87062975, -1.17851822,  3.0445436 ,  1.183562  ],
       [ 3.43237544, -2.94136739, -2.82893324, -0.70421186, -2.36889458],
       [ 2.68162828,  0.39902097, -1.41669396,  1.63207044,  0.46218627],
       [ 3.91044204,  0.2575232 , -1.68744468,  2.89664637,  1.58368114],
       [ 3.24253514,  1.88845356, -0.53253494, -1.9627949 , -1.81346913],
       [ 2.71906988, -1.4097544 , -4.06502571, -0.38200829, -1.22836944],
       [ 0.47829805,  0.31044368,  0.64661362,  2.65769757,  1.8125137 ],
       [ 0.77130909, -1.83012732, -1.11758078, -1.2210734 , -4.38025657],
       [ 3.65615298, -1.31572742, -4.50980916, -3.22157284, -4.92602138]])

In [26]:
# Active function(sigmoid Function)
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [31]:
a = sigmoid(h)
a

array([[0.95758139, 0.71542575, 0.22160136, 0.59411416, 0.68763687],
       [0.97123139, 0.13346887, 0.23531873, 0.95454637, 0.76558766],
       [0.96870117, 0.0501461 , 0.05578056, 0.33087907, 0.0855756 ],
       [0.93593383, 0.59845242, 0.19518039, 0.83645307, 0.61353269],
       [0.98036174, 0.56402734, 0.15611218, 0.94768041, 0.82972523],
       [0.96240395, 0.86857911, 0.36992585, 0.12316489, 0.14021937],
       [0.93814258, 0.1962728 , 0.01687296, 0.40564261, 0.22646694],
       [0.6173459 , 0.57699356, 0.65624694, 0.93448384, 0.8596654 ],
       [0.68380401, 0.13822311, 0.2464603 , 0.22774761, 0.01236728],
       [0.97481878, 0.21153002, 0.01088086, 0.03836192, 0.00720305]])

In [39]:
# Build a compeleted Network 
# def parameter 
x = np.random.randn(10, 2)

W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)

W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)

# def active function 
def sigmoid(x):
    return 1/(1 + np.exp(-x))

# first layer 
h1 = np.dot(x, W1) + b1
s = sigmoid(h1)
h2 = np.dot(s, W2) + b2

h2

array([[-0.44565602, -1.61534478, -0.27196843],
       [-0.19280041, -1.05201874,  1.67221258],
       [-0.4144735 , -1.93864131, -0.15121241],
       [-0.26867056, -1.34540693,  0.99443795],
       [-0.35049376, -1.29028645,  0.58611642],
       [-0.23942683, -1.3082477 ,  1.18826891],
       [-0.22906883, -1.57270212,  1.1430994 ],
       [-0.29593935, -1.10218419,  1.15092555],
       [-0.02746976, -1.03332957,  2.43301579],
       [-0.39829131, -2.27607555, -0.41630023]])

### 1.2.2 层的类化及正向传播的实现
- $forward():$ Direction from the input layer to output layer.   
- $backward():$ Propagate gradients in the reverse order of forward.

In [58]:
# Class active layer
class Sigmoid:
    def __init__(self):
        self.params = []
    def forward(self, x):   # only condsider forward
        return 1/(1 + np.exp(-x))

# Class Affine layer 
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
    def forward(self, x):
        W, b = self.params
        output = np.dot(x, W) + b
        return output    

#### TwoLayerNet Class

In [63]:
class TwolayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        # initial weight and bias
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        
        # Hidden Layer 
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ] 
        
        # Put weights in List.
        self.params = []
        for layer in self.layers:   # contain 3 layers' data from Affine, Sigmoid, Affine
            self.params += layer.params
        
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)    # call the forword from Class Sigmoid and Affine 
        return x    

In [66]:
# For example to predict 
x = np.random.randn(10, 2)
# Instantiate 
model = TwolayerNet(2, 4, 3)
# Prediction 
s = model.predict(x)