# Mathmatik and Python 

### 1.1.1  向量和矩阵

In [1]:
# Vector and Matrix 
# package
import numpy as np

In [2]:
x = np.array([1, 2, 3])
# x.__class__  # check the type; return numpy.ndarray
# x.shape      # check the shape; return (3,)
# x.ndim       # number of the dimensional;  return 1 
W = np.array([[1, 2, 3],[4, 5, 6]]) 


### 1.1.2  矩阵的对应元素的运算

In [3]:
# plus 
W + x
# mutiply
W * x

array([[ 1,  4,  9],
       [ 4, 10, 18]])

### 1.1.3 广播

In [6]:
# broadcast
A = np.array([[1, 2], [3, 4]])
A* 10 

array([[10, 20],
       [30, 40]])

In [7]:
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])

### 1.1.4 向量内机和矩阵乘积

In [3]:
# inneres Produkt
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a, b)

32

In [5]:
# matrix product
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])